### ISSUE TITLE
WinRAR and MOTW

### ISSUE THREAD

**Issue by jernejs** [nmantani/archiver-MOTW-support-comparison#1]
According to Eugene Roshal (WinRAR's author), WinRAR sets MOTW for Office formats, but not other types, because it was causing problems with some installers:

![image1](https://user-images.githubusercontent.com/1800143/166481522-8caaa24b-2acb-4c5e-9941-0c7fd07aa9ef.PnG)

> Hello,
> 
> It is intentional. Beginning from WinRAR 5.20 we set it only
> for MS Office file formats.
> 
> Some installers failed to work properly after assigning this stream
> and it hurt WinRAR reputation rather badly. For example, search for
> "Download 7Zip (I previously had winrar)" here:
> 
> https://rog.asus.com/forum/showthread.php?36977-How-to-Install-Ai-Suite-3!-(For-People-Who-Cannot-install-the-new-AI-Suite-3)/page5
> 
> Eugene
> 
> > It appears that at least WinRAR 6.11 doesn't propagate
> > mark-of-the-web (zone.identifier NTFS stream) when extracting files
> > from archives downloaded from the internet. Is this intentional?
> > IIRC, older versions did propagate MOTW.

**Comment by nmantani** [comment]
Thank you so much for valuable information! I have corrected the comparison table and added a note with https://github.com/nmantani/archiver-MOTW-support-comparison/commit/83b57b48ac6dc7b08c4dc51d72567231dd50bb29 .
