### ISSUE TITLE
7zip has MOTW now with version 22.00

### ISSUE THREAD

**Issue by SeriousHoax** [nmantani/archiver-MOTW-support-comparison#2]
It's disabled by default, but works as expected after enabling it:

![t](https://user-images.githubusercontent.com/29574622/174492968-11586d88-8de4-407a-b674-4e6dd80f0f9f.png)
![1](https://user-images.githubusercontent.com/29574622/174492977-afead5af-bd86-42b0-9588-9e8b3a71b2bb.png)
![2](https://user-images.githubusercontent.com/29574622/174492979-98b50196-476b-4d7a-826e-b8df0b62216d.png)

**Comment by nmantani** [comment]
Thank you for the information! I did some tests and updated the comparison table with additional information (supported file extensions for "Propagate Zone.Id stream"="For Office file" and registry setting).
