### ISSUE TITLE
Supported vs. Enabled

### ISSUE THREAD

**Issue by dobin** [nmantani/archiver-MOTW-support-comparison#3]
From the perspective of an attacker, if a software supports MOTW propagation, but it is not enabled by default, then its users are vulnerable (as noone changes the settings really). E.g. one can assume that 7zip does not propagate MOTW, even tho it supports it. 

Id recommend to have two rows: 
* MOTW propagation supported: Y/N
* MOTW propagation by default: Y/N

**Comment by nmantani** [comment]
Thank you for your suggestion! I have added "Enabled by default" column to the comparison table.

**Comment by dobin** [comment]
Cool beans, exactly what i needed .
