### ISSUE TITLE
WinRar updated list of supported types and defaults

### ISSUE THREAD

**Issue by ThioJoe** [nmantani/archiver-MOTW-support-comparison#4]
Found this repo while researching for a video I'm making and it's very valuable, I'll be sure to give it a mention 👍

I have some updated info for [Note #7](https://github.com/nmantani/archiver-MOTW-support-comparison?tab=readme-ov-file#*7)

I just tested the latest version of Winrar (7.01) and it looks like now it actually shows you exactly which filetypes propogate MoTW in the Settings > "Security" Tab:

<img width="550" alt="image" src="https://github.com/user-attachments/assets/bc8ef462-01fe-47e8-82e4-24d8ce1fb578">

And it defaults to "executables and office files", though there are other options:

<img width="550" alt="image" src="https://github.com/user-attachments/assets/c24de485-e673-44c6-b3cb-177bb741b903">

The text box with the list of extensions changes with the different selections, so you can see which will be propagated for each option. It looks like the feature was added in [version 7.00](https://www.win-rar.com/singlenewsview.html?&L=0&tx_ttnews%5Btt_news%5D=251&cHash=843e9e875ad0ca0e28e4b14ef34d17cd#:~:text=Security%20and%20Compatibility,and%20compatibility%20standards.)

**Comment by nmantani** [comment]
Hi, I missed the new "Propagate Mark of the Web" option when I tested WinRAR 7.01.
I have updated the note of WinRAR. Thank you so much!
